apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: default
  labels:
    app: envoy
spec:
  type: ClusterIP
  selector:
    app: envoy
  ports:
    - port: 10001
      targetPort: 10001
      name: http-ingress
    - port: 9901
      targetPort: 9901
      name: admin-metrics