apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: shadowcast-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: shadowcast.rules
      rules:
        - alert: ShadowTrafficDrift
          expr: |
            (
              (sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name="shadow-service"}[1m])) or vector(0))
              / on()
              (sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name="order-service"}[1m])) or vector(1))
            ) < 0.90
          for: 15s
          labels:
            severity: warning
          annotations:
            summary: "Shadow traffic drop detected"
            description: "Shadow service is receiving less than 90% of primary traffic or is down."