apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:latest
          args:
            - "-text=ORDER_SERVICE_PRIMARY"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-service
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: shadow-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadow-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shadow-service
  template:
    metadata:
      labels:
        app: shadow-service
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:latest
          args:
            - "-text=SHADOW_SERVICE_MIRROR"
            - "-listen=:8080"
          ports:
            - containerPort: 8080