apiVersion: traffic.shadowcast.io/v1alpha1
kind: ShadowPolicy
metadata:
  name: order-shadow-policy
  namespace: default
spec:
  sourceService: order-service
  targetService: shadow-service
  mirrorPercentage: 100