apiVersion: traffic.shadowcast.io/v1alpha1
kind: ShadowPolicy
metadata:
  name: shadowpolicy-sample
  namespace: default
spec:
  sourceService: order-service
  targetService: shadow-service
  mirrorPercentage: 100
  headers:
    - name: "x-shadow-test"
      exact: "true"